### ISSUE TITLE
Grafana makes CrateDB crash

### ISSUE THREAD

**Issue by AngeloIapichino** [smartsdk/ngsi-timeseries-api#253] opened 2019-09-23 13:25 UTC
Hi guys,

I installed FIWARE components through docker compose file following this page: https://quantumleap.readthedocs.io/en/latest/admin/

While data are sent from the Broker to CrateDB, Grafana comes slower and slowe until CrateDB crashes.

I'm sure that is Grafana that make CrateDB crash because if nobody open a dashboard in Grafana, CrateDB continues to live.

What can i do for avoiding this slowing and crashing?

Thanks in advance for the answers.

**Comment by chicco785** [comment] 2019-09-23 13:49
hi @AngeloIapichino 
it is hard to reply to your question:
1. you haven't provided any concrete information on the deployment neither simple way to reproduce the bag;
1. clearly this is not anything specific to quantumleap, but rather a problem of crate related to your environment.

now, my wild guess is that your are poor on ram in your docker machine, and that when it saturates, due to queries, your deployment gets first slow and the crash.

**Comment by AngeloIapichino** [comment] 2019-09-23 14:19
Deployment with this docker-compose file:

> version: '3'
> 
> services:
> 
>   orion:
>     image: fiware/orion:${ORION_VERSION:-2.2.0}
>     ports:
>       - "1026:1026"
>     command: -logLevel DEBUG -noCache -dbhost mongo -corsOrigin __ALL
>     depends_on:
>       - mongo
>     healthcheck:
>       test: ["CMD", "curl", "-f", "http://0.0.0.0:1026/version"]
>       interval: 1m
>       timeout: 10s
>       retries: 3
> 
>   mongo:
>     image: mongo:3.2.19
>     ports:
>       - "27017:27017"
>     volumes:
>       - mongodata:/data/db
> 
>   quantumleap:
>     image: ${QL_IMAGE:-smartsdk/quantumleap}
>     ports:
>       - "8668:8668"
>     depends_on:
>       - mongo
>       - orion
>       - crate
>     environment:
>       - CRATE_HOST=${CRATE_HOST:-crate}
>       - USE_GEOCODING=True
>       - REDIS_HOST=redis
>       - REDIS_PORT=6379
> 
>   crate:
>     image: crate:${CRATE_VERSION:-3.1.2}
>     command: crate -Clicense.enterprise=false -Cauth.host_based.enabled=false
>       -Ccluster.name=democluster -Chttp.cors.enabled=true -Chttp.cors.allow-origin="*"
>     ports:
>       # Admin UI
>       - "4200:4200"
>       # Transport protocol
>       - "4300:4300"
>       - "5432:5432"
>     volumes:
>       - cratedata:/data
> 
>   grafana:
>     image: grafana/grafana
>     ports:
>       - "3000:3000"
>     environment:
>       - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-worldmap-panel,flant-statusmap-panel
>       - GF_PANELS_DISABLE_SANITIZE_HTML=true
>     depends_on:
>       - crate
>     volumes:
>       - grafanadata:/var/lib/grafana
> 
>   redis:
>     image: redis
>     deploy:
>       # Scaling Redis requires some extra work.
>       # See https://get-reddie.com/blog/redis4-cluster-docker-compose/
>       replicas: 1
>     ports:
>       - "6379:6379"
>     volumes:
>       - redisdata:/data
> 
> volumes:
>   mongodata:
>   cratedata:
>   redisdata:
>   grafanadata:
> 
> networks:
>     default:
>         driver_opts:
>             com.docker.network.driver.mtu: ${DOCKER_MTU:-1400}

I have about 14k records.

Do you think that the problem is the deployment (all in a local and docker machine)? Can you suggest a different way to deploy it?

Thanks in advance.

**Comment by chicco785** [comment] 2019-09-23 14:41
As said, I think the issue is the memory, but it's a guess. You can:
1) check the logs of the different components and try to guess what's going wrong; 2) measure (with top) resources in the docker machine to see if you are hitting memory limit; 3) see what happens if you increase memory assigned to your virtual machine.

**Comment by AngeloIapichino** [comment] 2019-09-23 15:10
I know that the problem is the memory because CrateDB crashes with outofmemoryerror.
The question is: the solution can be only increasing the memory or maybe i have to change the deployment approach (i read about HA deployment)?

**Comment by chicco785** [comment] 2019-09-23 15:26
i am not sure that just going HA will solve your memory issue :) you should just make proper amount of memory available in your docker machine.

anyhow, if you wanna use docker swarm:
https://smartsdk-recipes.readthedocs.io/en/latest/data-management/quantumleap/readme/

alternatively, on kubernetes:
https://github.com/orchestracities/charts

**Comment by AngeloIapichino** [comment] 2019-10-08 13:58
I solved the crashes increasing the crate's heap space memory setting the environment variable CRATE_HEAP_SIZE to 3 giga.
In the docker-compose file:

```
crate:
    image: crate:${CRATE_VERSION:-3.1.2}
    environment:
      - CRATE_HEAP_SIZE=3000M
    command: crate -Clicense.enterprise=false -Cauth.host_based.enabled=false
      -Ccluster.name=democluster -Chttp.cors.enabled=true -Chttp.cors.allow-origin="*"
    ports:
      # Admin UI
      - "4200:4200"
      # Transport protocol
      - "4300:4300"
      - "5432:5432"
    volumes:
      - cratedata:/data

```

Grafana is still very slow and laggy, but i'm doing some test increasing the RAM amount of the machine.

**Comment by chicco785** [comment] 2019-10-08 15:02
Be careful with heap memory, it should not be more than half of the actual memory available on your machine, or you will end up swapping. https://crate.io/docs/crate/guide/en/latest/performance/memory.html#mobile-nav

**Comment by chicco785** [comment] 2019-10-15 19:10
Can we consider this issue closed?

**Closed** 2020-04-12 19:43 UTC
Labels: question

**Comment by amotl** [comment] 2020-12-04 14:28
Hi there,

even when coming late to this, I would like to add that swapping can be avoided for CrateDB by configuring `bootstrap.memory_lock: true`, see also [1]. But still, @chicco785 is right - a good starting point for the heap space is 25% of the system memory.

With kind regards,
Andreas.

[1] https://crate.io/docs/crate/howtos/en/latest/performance/memory.html#swap
