### ISSUE TITLE
time_index only in seconds?

### ISSUE THREAD

**Issue by AngeloIapichino** [smartsdk/ngsi-timeseries-api#197] opened 2019-05-23 17:16 UTC
Hi guys, i'm new in FIWARE.

I'm wondering why if i send to the broker messages with a time interval < 1 second i get this behaviour (more record in same second):

![image](https://user-images.githubusercontent.com/12069840/58272401-b65eb980-7d8e-11e9-80c5-89aaf5b6b518.png)

I want to use milliseconds in my project.

Any advice?

Thanks in advance

**Comment by taliaga** [comment] 2019-05-23 17:33
Hi there!

QL processes `time_index` with precision of milliseconds so that shouldn't be a problem.

You need to make sure the Orion subscription has no throttling to actually get more than 1 per second. But that what you show, 4 times the same instant, looks weird. I've seen sometimes a duplicate of two, specially with the first notification Orion sends, but not more than that.

What does your subscription look like? which Orion and QL versions do you have?.

**Comment by AngeloIapichino** [comment] 2019-05-23 18:30
Orion version: 2.2.0
QL version: 0.6

I made subscription using QL API:
POST url = 'http://host8668/v2/subscribe' 
With this data {
          "orionUrl": 'http://orion:1026/v2',  "quantumleapUrl":'http://quantumleap:8668/v2',
          "entityType": entityType
        }

**Comment by chicco785** [comment] 2019-05-24 08:28
@AngeloIapichino most probably the problem is what orion sends to ql. please check that `dateModified` does not include milliseconds. also, refer to the [time-index](https://quantumleap.readthedocs.io/en/latest/user/#time-index) discussion to see how to use alternative columns as `time_index`

**Comment by ohylli** [comment] 2019-05-27 07:41
Orion does not support milliseconds. See for example [this issue](https://github.com/telefonicaid/fiware-orion/issues/3412).

**Comment by AngeloIapichino** [comment] 2019-05-27 08:04
Thanks ohylli! We get the problem know...

**Comment by ohylli** [comment] 2019-05-27 08:33
If you insert directly to QuantumLeap via its notify API I think it will then keep the milliseconds.

**Comment by chicco785** [comment] 2019-05-27 09:47
AFAIK, it supports it for but not for default dateCreatetion
dateModification

**Comment by chicco785** [comment] 2019-05-29 13:30
i suppose we can close the issue, if not please, let us know, we will re-open it

**Closed by chicco785** 2019-05-29 13:30 UTC
Labels: question
