### ISSUE TITLE
Something went wrong with QL

### ISSUE THREAD

**Issue by josselin-pierre** [smartsdk/ngsi-timeseries-api#368] opened 2020-09-23 08:13 UTC
QuantumLeap used to work, but for some time now it returns `"Something went wrong with QL. Error: SQLActionException[SQLParseException: Invalid index name: mtdefault]"` when I try to access entity history.
QuantumLeap 0.7.6 with docker and docker-compose on debian 9.

**orion**
http://host:1026/v2/entities/test
`{
    "id": "test",
    "type": "test",
    "temperature": 19
}`

http://host:1026/v2/subscriptions/test
`{
        "id": "5f6afd0271c7d684323e715c",
        "status": "active",
        "subject": {
            "entities": [
                {
                    "id": "test",
                    "type": "test"
                }
            ],
            "condition": {
                "attrs": [
                    "temperature"
                ]
            }
        },
        "notification": {
            "timesSent": 1,
            "lastNotification": "2020-09-23T07:45:06.131Z",
            "attrs": [
                "temperature"
            ],
            "attrsFormat": "normalized",
            "http": {
                "url": "http://quantumleap:8668/v2/notify"
            }
        }
    }`

**quantum leap**
http://host:8668/v2/entities/anything
(with any entity, existing or not)
`"Something went wrong with QL. Error: SQLActionException[SQLParseException: Invalid index name: mtdefault]"`

http://host:8668/version
`{ "version": "0.7.6" }`

http://host:8668/health
`{ "status": "pass" }`
200

Docker-compose log
quantumleap_1       | Something went wrong with QL. Error: SQLActionException[SQLParseException: Invalid index name: mtdefault]
quantumleap_1       | Traceback (most recent call last):
quantumleap_1       |   File "/src/ngsi-timeseries-api/src/reporter/query_1T1ENA.py", line 45, in query_1T1ENA
quantumleap_1       |     entities = trans.query(attr_names=attrs,
quantumleap_1       |   File "/src/ngsi-timeseries-api/src/translators/sql_translator.py", line 713, in query
quantumleap_1       |     entity_type = self._get_entity_type(entity_id, fiware_service)
quantumleap_1       |   File "/src/ngsi-timeseries-api/src/translators/sql_translator.py", line 1073, in _get_entity_type
quantumleap_1       |     self.cursor.execute(stmt, [entity_id, ])
quantumleap_1       |   File "/usr/local/lib/python3.8/site-packages/crate/client/cursor.py", line 53, in execute
quantumleap_1       |     self._result = self.connection.client.sql(sql, parameters,
quantumleap_1       |   File "/usr/local/lib/python3.8/site-packages/crate/client/http.py", line 331, in sql
quantumleap_1       |     content = self._json_request('POST', self.path, data=data)
quantumleap_1       |   File "/usr/local/lib/python3.8/site-packages/crate/client/http.py", line 458, in _json_request
quantumleap_1       |     _raise_for_status(response)
quantumleap_1       |   File "/usr/local/lib/python3.8/site-packages/crate/client/http.py", line 187, in _raise_for_status
quantumleap_1       |     raise ProgrammingError(error.get('message', ''),
quantumleap_1       | crate.client.exceptions.ProgrammingError: SQLActionException[SQLParseException: Invalid index name: mtdefault]
quantumleap_1       | host - - [23/Sep/2020 07:56:44] "GET /v2/entities/anything HTTP/1.1" 500 -

**Comment by c0c0n3** [comment] 2020-09-23 08:42
Hello @josselin-pierre, thanks for using QuantumLeap. The error trace hints at a problem with your Crate schema. Can you check if there's a schema called `mtdefault`? My guess is that all your entities where in that schema and at some point some other process or script dropped the schema? Or did you upgrade Crate skipping a major version?

**Comment by josselin-pierre** [comment] 2020-09-23 09:06
@c0c0n3 Thank for your reply, i'm using Crate 3.1.6 and I haven't upgraded it.
But i have probably upgraded quatum leap from 0.7.5 to latest.
Sorry but i am not familiar with crate, how can i connect to it to do a query ?

**Comment by c0c0n3** [comment] 2020-09-23 09:26
> Thank for your reply

Pleasure!

> using Crate 3.1.6 and I haven't upgraded it.
> upgraded quatum leap from 0.7.5 to latest.

Okay, there could be a QuantumLeap backward compat issue but let's first try to rule out the obvious, i.e. making sure the schema is there. You should be able to just browse to the Crate admin console at `http://your-crate-host:4200`---assuming you deployed vanilla Crate without tweaking any config. From there you should be able to see what tables and schemas are in your DB.

**Comment by josselin-pierre** [comment] 2020-09-23 09:57
A graphical interface, better than expected!

Here are the existing tables in Crate : 
![image](https://user-images.githubusercontent.com/71328058/93997181-64b7ac00-fd93-11ea-9f55-7f20c68f49e4.png)

There is indeed a table mtdefault.ettest :
![image](https://user-images.githubusercontent.com/71328058/93997296-89138880-fd93-11ea-862b-67d58e3ca4f3.png)

**Comment by josselin-pierre** [comment] 2020-09-23 09:58
Data are correctly saved in Crate :
![image](https://user-images.githubusercontent.com/71328058/93997824-1951cd80-fd94-11ea-99b3-76b33c13a5f3.png)

**Comment by c0c0n3** [comment] 2020-09-24 06:21
@josselin-pierre thanks for this. Is there any chance you could post here your docker compose file too? That'd help us debugging...

**Comment by chicco785** [comment] 2020-09-24 07:17
@josselin-pierre i would revert to 0.7.5, i don't think - also by doc - we support anymore crate 3.1.6 with newer versions

**Comment by josselin-pierre** [comment] 2020-09-24 07:27
@c0c0n3 sure

.env
https://pastebin.com/vrTVu3AN

docker-compose.yml
https://pastebin.com/khmhR5Cp

@chicco785
I tried to revert QL to 0.7.5 but it still not working.
I also tried to upgrade Crate to 3.3.5, same problem.

But if it's a specific problem don't bother, I've deployed a new clean install of all modules and it's working again.
But this time with QL 0.7.6 and Crate 3.3.X and I froze versions so that it doesn't happen anymore!

**Comment by c0c0n3** [comment] 2020-09-24 07:56
> But if it's a specific problem don't bother, I've deployed a new clean install of all modules and it's working again.

Glad to hear that! Also I tried to reproduce myself using the docker compose file you posted above, but everything went smoothly, I could create a default tenant with test entities and then retrieve the entities through the API. If I had to guess, I'd say the backing Lucene index on  your old`/data` got corrupted, but have no idea how or why.

Since it doesn't look like there's anything we can do about this, I'm closing this issue. @josselin-pierre please feel free to reopen it if you think we have a backward compat problem and we'll dig deeper.

**Closed by c0c0n3** 2020-09-24 07:56 UTC
Labels: bug or fix
